name: Deploy DAGs to S3 for MWAA

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-central-1'  # Replace with your MWAA region

      - name: Sync DAGs to S3
        run: aws s3 sync ./dags/ s3://airflow-setting/dags/ --delete
      - name: Sync requirements.txt to S3
        run: aws s3 sync requirements.txt s3://airflow-setting/requirements.txt --delete